api:
  github:
    service-path: https://api.github.com
    search-api-url: /search/repositories
    sort-by: stars
    order-by: desc
    date-parameter: created
    language: language
    query: ?q={query}&sort={sort}&order={order}&per_page={limit}

